// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Barrier;

  Barrier = (function() {
    function Barrier() {}

    Barrier.prototype.read = function() {};

    return Barrier;

  })();

  module.exports = Barrier;

}).call(this);
