// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Consumer,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Consumer = (function() {
    function Consumer() {
      this.read = __bind(this.read, this);
      this.load = __bind(this.load, this);
      this.store = __bind(this.store, this);
    }

    Consumer.prototype.store = function(sequence) {
      this.sequence = sequence;
    };

    Consumer.prototype.load = function() {
      return this.sequence;
    };

    Consumer.prototype.read = function() {
      return this.sequence;
    };

    return Consumer;

  })();

  module.exports = Consumer;

}).call(this);
