// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Cursor, InitialSequenceValue, cpuCacheLinePadding;

  InitialSequenceValue = -1;

  cpuCacheLinePadding = require('os').cpus().length - 1;

  Cursor = (function() {
    function Cursor() {
      this.sequence = InitialSequenceValue;
      this.padding = new Array(cpuCacheLinePadding);
    }

    return Cursor;

  })();

  module.exports = Cursor;

}).call(this);
